/*
 *  jDTAUS - DTAUS fileformat.
 *  Copyright (C) 2005 Christian Schulte <cs@schulte.it>
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */
package org.jdtaus.common.directories.impl.germany;

import org.jdtaus.common.TechnicalError;

/**
 * Strategy for account code validators.
 *
 * @author <a href="mailto:cs@schulte.it">Christian Schulte</a>
 * @version $Id$
 */
public interface AccountCodeValidator {
    
    //--Specification-----------------------------------------------------------

    // This section is generated by jdtaus-source-plugin.

    /** Unique key of this specification. */
    public static final String SPEC = AccountCodeValidator.class.getName();

    //-----------------------------------------------------------Specification--
    //--AccountCodeValidator----------------------------------------------------
    
    /**
     * Validates a given account number.
     *
     * @return {@code true} if {@code accountCode} describes a valid
     * account code; {@code false} if not.
     *
     * @throws TechnicalError for unrecoverable errors.
     */
    boolean isAccountCodeValid(long accountCode) throws TechnicalError;
    
    //----------------------------------------------------AccountCodeValidator--
    
}
